[package]
name = "zincboy"
version = "0.1.0"
authors = ["Dhole <dhole@riseup.net>"]
edition = "2018"
build = "build.rs"

[dependencies]
enum-map = "0.4.1"
arrayref = "0.3.5"

[build-dependencies]
maplit = "1.0.1"
Inflector = "*"
